### ISSUE TITLE
update fellowship subnav

### ISSUE THREAD

**Issue by kissane** [mozilla/mozilla-opennews#202]
![screen shot 2015-01-15 at 12 47 33 pm](https://cloud.githubusercontent.com/assets/1910034/5763030/b67e40bc-9cb4-11e4-9680-24e4c5ebd52d.png)

Need to match to fellowship pages in the sidebar menu and title case

**Comment by kissane** [comment]
fixed, have submitted PR for testing

**Comment by sinker** [comment]
Hmmmm. was this fixed in #209?

**Comment by kissane** [comment]
Should have been

**Comment by sinker** [comment]
can you check? is up on staging now. I just don't know what was there previously vs what ended up in the change.

**Comment by kissane** [comment]
I'm not seeing most of my changes on staging—that is still the same as it was last night

**Comment by sinker** [comment]
was not among the files in your PR: https://github.com/sinker/mozilla-opennews/pull/24/files

**Comment by kissane** [comment]
I guess my add --all didn't go. Working on it now.

**Comment by kissane** [comment]
This is tested and done.
